# Linear Algebra


Linear algebra is a mathematical toolbox that offers helpful techniques for manipulating groups of numbers simultaneously. It provides structures like vectors and matrices (spreadsheets) to hold these numbers and new rules for how to add, subtract, multiply, and divide them. 

![assets/linearAlgebraExample.PNG](assets/linearAlgebraExample.png)


## 1. Vectors

Vectors are 1-dimensional arrays of numbers or terms. In geometry, vectors store the magnitude and direction of a potential change to a point. The vector [3, -2] says go right 3 and down 2. A vector with more than one dimension is called a matrix.


### 1.1 Notation

There are a variety of ways to represent vectors. Here are a few you might come across in your reading.

![assets/vectors.PNG](assets/vectorNotation.png)


### 1.2 Vectors in geometry

Vectors typically represent movement from a point. They store both the magnitude and direction of potential changes to a point. The vector [-2,5] says move left 2 units and up 5 units.

![image.png](assets/vectors.PNG)

A vector can be applied to any point in space. The vector's direction equals the slope of the hypotenuse created moving up 5 and left 2. Its magnitude equals the length of the hypotenuse.


### 1.3 Scalar operations

Scalar operations involve a vector and a number. You modify the vector in-place by adding, subtracting, or multiplying the number from all the values in the vector.

![image.png](assets/scalarOperations.png)


### 1.4 Elementwise operations

In elementwise operations like addition, subtraction, and division, values that correspond positionally are combined to produce a new vector. The 1st value in vector A is paired with the 1st value in vector B. The 2nd value is paired with the 2nd, and so on. This means the vectors must have equal dimensions to complete the operation.*

![image.png](assets/elementWiseOperations.png)


See below for details on broadcasting in numpy.

In [3]:
import numpy as np

y = np.array([1,2,3])
x = np.array([2,3,4])

print(x + y)
print(x - y)
print(x / y)

[3 5 7]
[1 1 1]
[2.         1.5        1.33333333]


### 1.5 Dot product

The dot product of two vectors is a scalar. Dot product of vectors and matrices (matrix multiplication) is one of the most important operations in deep learning.

![image.png](assets/dotProduct.png)




In [4]:
y = np.array([1,2,3])
x = np.array([2,3,4])
np.dot(y,x)

20

### 1.6 Hadamard product

Hadamard Product is elementwise multiplication and it outputs a vector.

![image.png](assets/hadamardProduct.png)



In [5]:
y = np.array([1,2,3])
x = np.array([2,3,4])
y * x 

array([ 2,  6, 12])


## 2. Matrices

A matrix is a rectangular grid of numbers or terms (like an Excel spreadsheet) with special rules for addition, subtraction, and multiplication.

### 2.1 Dimensions

We describe the dimensions of a matrix in terms of rows by columns.

![image.png](assets/dimensions.png)

The first has dimensions (3,2). The second (2,3).




In [7]:

a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
b = np.array([[1,2,3]])
print(b.shape)


(2, 3)
(1, 3)


### 2.2 Scalar operations

Scalar operations with matrices work the same way as they do for vectors. Simply apply the scalar to every element in the matrix - add, subtract, divide, multiply, etc.

![image.png](assets/MatrixScalarOperations.png)



In [8]:
# Addition
a = np.array(
[[1,2],
 [3,4]])
print(a + 1)

[[2 3]
 [4 5]]



### 2.3 Elementwise operations

In order to add, subtract, or divide two matrices they must have equal dimensions. We combine corresponding values in an elementwise fashion to produce a new matrix.

![image.png](assets/MatrixElementWiseOperations.png)





In [10]:

a = np.array([
 [1,2],
 [3,4]])
b = np.array([
 [1,2],
 [3,4]])

print(a + b)

print(a - b)


[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


### 2.4 Hadamard product

Hadamard product of matrices is an elementwise operation. Values that correspond positionally are multiplied to produce a new matrix.

![image.png](assets/MatrixHadamardProduct.png)


In numpy you can take the Hadamard product of a matrix and vector as long as their dimensions meet the requirements of broadcasting.

![image.png](assets/MatrixHadamardProduct1.png)




In [11]:

a = np.array(
[[2,3],
 [2,3]])
b = np.array(
[[3,4],
 [5,6]])

# Uses python's multiply operator
print(a * b)


[[ 6 12]
 [10 18]]


### 2.5 Matrix transpose

Neural networks frequently process weights and inputs of different sizes where the dimensions do not meet the requirements of matrix multiplication. Matrix transposition (often denoted by a superscript 'T' e.g. M^T) provides a way to "rotate" one of the matrices so that the operation complies with multiplication requirements and can continue. There are two steps to transpose a matrix:



1. Rotate the matrix right 90°
2. Reverse the order of elements in each row (e.g. [a b c] becomes [c b a])

As an example, transpose matrix M into T:

![image.png](assets/MatrixTranspose.png)




In [12]:

a = np.array([
   [1, 2],
   [3, 4]])

a.T


array([[1, 3],
       [2, 4]])

### 2.6 Matrix multiplication

Matrix multiplication specifies a set of rules for multiplying matrices together to produce a new matrix.

**Rules**

Not all matrices are eligible for multiplication. In addition, there is a requirement on the dimensions of the resulting matrix output. Source.



1. The number of columns of the 1st matrix must equal the number of rows of the 2nd
2. The product of an M x N matrix and an N x K matrix is an M x K matrix. The new matrix takes the rows of the 1st and columns of the 2nd

**Steps**

Matrix multiplication relies on dot product to multiply various combinations of rows and columns. In the image below, taken from Khan Academy's excellent linear algebra course, each entry in Matrix C is the dot product of a row in matrix A and a column in matrix B.

![image.png](assets/MatrixMultiplication.png)

The operation a1 · b1 means we take the dot product of the 1st row in matrix A (1, 7) and the 1st column in matrix B (3, 5).

![image.png](assets/MatrixMultiplication1.png)

Here's another way to look at it:

![image.png](assets/MatrixMultiplication2.png)



### 2.7 Test yourself

1. What are the dimensions of the matrix product?

![image.png](assets/Question1.PNG)

2. What are the dimensions of the matrix product?

![image.png](assets/Question2.PNG)

3. What is the matrix product?

![image.png](assets/Question3.PNG)

4. What is the matrix product?

![image.png](assets/Question4.PNG)

5. What is the matrix product?

![image.png](assets/Question5.PNG)



## 3. Numpy

### 3.1 Dot product

Numpy uses the function np.dot(A,B) for both vector and matrix multiplication. It has some other interesting features and gotchas so I encourage you to read the documentation here before use.




In [13]:

a = np.array([
 [1, 2]
 ])

b = np.array([
 [3, 4],
 [5, 6]
 ])

print(a.shape, b.shape)
# Multiply
mm = np.dot(a,b)
print(mm)

(1, 2) (2, 2)
[[13 16]]



### 3.2 Broadcasting

In numpy the dimension requirements for elementwise operations are relaxed via a mechanism called broadcasting. Two matrices are compatible if the corresponding dimensions in each matrix (rows vs rows, columns vs columns) meet the following requirements:



1. The dimensions are equal, or
2. One dimension is of size 1



In [15]:

a = np.array([
 [1],
 [2]
])
b = np.array([
 [3,4],
 [5,6]
])
c = np.array([
 [1,2]
])

# Same no. of rows
# Different no. of columns
# but a has one column so this works
print(a * b)

# Same no. of columns
# Different no. of rows
# but c has one row so this works
print(b * c)


# Different no. of columns
# Different no. of rows
# but both a and c meet the
# size 1 requirement rule
print(a + c)


[[ 3  4]
 [10 12]]
[[ 3  8]
 [ 5 12]]
[[2 3]
 [3 4]]


Tutorials

* [Khan Academy Linear Algebra](https://medium.com/r/?url=https%3A%2F%2Fwww.khanacademy.org%2Fmath%2Flinear-algebra)
* [Deep Learning Book Math](https://medium.com/r/?url=http%3A%2F%2Fwww.deeplearningbook.org%2Fcontents%2Fpart_basics.html)
* [Andrew Ng Course Notes](https://medium.com/r/?url=https%3A%2F%2Fwww.coursera.org%2Flearn%2Fmachine-learning%2Fresources%2FJXWWS)
* [Linear Algebra Better Explained](https://medium.com/r/?url=https%3A%2F%2Fbetterexplained.com%2Farticles%2Flinear-algebra-guide%2F)
* [Understanding Matrices Intuitively](https://medium.com/r/?url=http%3A%2F%2Fblog.stata.com%2F2011%2F03%2F03%2Funderstanding-matrices-intuitively-part-1%2F)
* [Intro To Linear Algebra](https://medium.com/r/?url=http%3A%2F%2Fwww.holehouse.org%2Fmlclass%2F03_Linear_algebra_review.html)
* [Immersive Math](https://medium.com/r/?url=http%3A%2F%2Fimmersivemath.com%2Fila%2Findex.html)
* [Linear Algebra](https://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html)